### ISSUE TITLE
[bugs] some issues i found

### ISSUE THREAD

**Issue by BamsTheSergal** [Nebual/sandbox-plus#7] opened 2023-08-11 16:09 UTC
not sure if its just temp or not working, but the screen on the toolgun is not there, and in third person the toolgun is like 90 degrees right, trails still follow it funnily enough. 

in the dynplates menu if you do not press enter, you are locked in the spawn screen till you do.

undo seems to not work, if that's not in yet then maybe that's why.

**Comment by Nebual** [comment] 2023-08-11 20:03
The toolgun fixes #6 were merged last night, and I thought I published a new build on asset.party but I was having some trouble with the recompiling step (seems to have some s&box bugs...) so maybe the published one is missing that somehow...

That Dynplates menu is definitely pretty rough UX - it is intentional that the spawnmenu stays open when you let go of Q while in a textfield in the menu, I believe Gmod had this same behaviour - but if thats not what you're observing, it might be a regression.

I don't fully understand how keybinds/Actions work in the current APIs, but I've consistently had Undo working fine since I added it to S+ last week - do you perhaps need to bind Undo in the Settings page when starting a server?

**Comment by BamsTheSergal** [comment] 2023-08-12 01:16
its probably the last part, but no such issues than that so far, very cool work

the dynplates i ment like if you dont press enter, it will lock you in the spawn menu entirely, till you go back to that page, then press enter

there currently isnt a way to bind it from the ingame settings menu, but the undo works by making a console command bind.

**Comment by BamsTheSergal** [comment] 2023-08-12 04:01
i found another weird bug, if you undo a welded wire entity it insta crashes

**Comment by Nebual** [comment] 2023-08-12 21:57
Fixed Undo not having a keybind!

I'm not able to reproduce that crash, can you be more specific about what you did?

**Comment by BamsTheSergal** [comment] 2023-08-13 19:48
basically this, i think i did say it pretty weird.

https://github.com/Nebual/sandbox-plus/assets/12705993/ffc70621-3c99-482c-8108-f897bfded593

**Comment by ninjrdevelop** [comment] 2024-12-28 04:14
Honestly it's probably worth closing this, as things have changed a lot since. We should reopen if replicable in new code.

**Closed by ninjrdevelop** 2024-12-28 04:14 UTC
Labels: bug

**Comment by BamsTheSergal** [comment] 2024-12-28 13:04
not a prob, makes sense lol
